language: node_js
node_js:
    - "8.11.1"
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
    - export PATH="$HOME/.yarn/bin:$PATH"
    - yarn install
script:
    - yarn build
cache:
    yarn: true
    directories:
        - node_modules

